Iter24
nextlag/shortenerURL pull request #102
Opened 2024-07-11 05:12 UTC by nextlag

2024-07-14 23:02 UTC, avhitrov requested changes
Раз в мои лапы попался клон изменений с прошлого ПР, я посмотрел на него более внимательно и обнаружил отсутствие реализации обратной совместимости по функциям удаления и работой с UserID.

Кроме того, есть замечание по организации graceful shutdown.

2024-07-14 23:02 UTC, avhitrov commented on internal/usecase/storage.go
> +func (s *Data) Del(_ int, _ []string) error {
Я, видимо, проглядел в прошлых итерациях. А, собственно, почему для in-memory не реализованы работа с пользователем и операция удаления?

Это, в общем, несложно, если вместо `data  map[string]string` использовать `data  map[string]UrlData`, где UrlData будет структурой с полями, включающими в себя, в том числе IsDeleted и UserID.

Я советовался с авторами курса и другими менторами, все сходятся в том, что обратную совместимость по всем реализуемым функциям необходимо делать для всех стораджей.

2024-07-15 18:00 UTC, nextlag commented on internal/usecase/storage.go
> +func (s *Data) Del(_ int, _ []string) error {
потому, что этого нет в ТЗ, второе: чтобы это сделать не достаточно реализовать data  map[string]UrlData - все данные должны храниться в файлах. Нужно будет реализовать полноценный WAL - это выходит за рамки текущего техзадания. Иначе для этого были бы написаны автотесты!

2024-07-30 22:31 UTC, avhitrov approved these changes
Данный ПР принимается, все комментарии переносим в ПР 105.

2024-07-31 05:30 UTC, merged