Iter25
nextlag/shortenerURL pull request #105
Opened 2024-07-15 18:25 UTC by nextlag

2024-07-15 18:29 UTC, nextlag commented
по поводу обратной совместимости для filestorage: этого нет в ТЗ, с моего потока никто этого не делал, автотесты это также не проверяют; второе: чтобы это сделать не достаточно реализовать data map[string]UrlData - все данные должны храниться в файлах. Нужно будет реализовать полноценный WAL - это выходит за рамки текущего техзадания! и третье, у меня уже почти не осталось времени закончить этот курс, а еще писать итоговый проект. Прошу не обращать на это внимание

2024-07-22 08:01 UTC, nextlag commented
Сделал обратную совместимость

2024-07-22 23:02 UTC, avhitrov requested changes
Если не считать того, что в рамках одной проверки сильно раздут scope, реализация вполне успешная. Забыт один хендлер gRPC и есть комментарии по унификации стораджей.

2024-07-23 00:13 UTC, nextlag commented on internal/usecase/storage.go
> +	del   map[string]*dataDel
я делал так, в таком случае нарушается логика проверки автотестов. Они ожидают, что в файл кладутся 3 параметра: uuid, alias, ulr. Поэтому я создал отдельный файл, чтобы автотесты не фейлились.

2024-07-23 11:18 UTC, nextlag commented on internal/controllers/grpc/grpc_handler.go
> +
добавил

2024-07-23 11:18 UTC, nextlag commented on internal/usecase/dbstorage.go
> +}
вынес

2024-07-23 11:19 UTC, nextlag commented on internal/usecase/dbstorage.go
> +func (uc *UseCase) GetAll(ctx context.Context, id int, host string) ([]byte, error) {
реализовал

2024-07-23 11:19 UTC, nextlag commented on internal/usecase/dbstorage.go
> +func (uc *UseCase) Del(id int, aliases []string) error {
согласен, тупанул

2024-07-31 05:39 UTC, nextlag commented
комментарии с 24 PR остались здесь https://github.com/nextlag/shortenerURL/pull/102 - как их перенести в в iter25 - я не совсем понимаю

2024-08-06 20:17 UTC, avhitrov approved these changes
Вроде все ок. Мои поздравления с завершением проекта.

2024-08-06 20:31 UTC, merged