Iter18
nextlag/shortenerURL pull request #77
Opened 2024-06-22 13:40 UTC by nextlag

2024-06-27 21:45 UTC, avhitrov requested changes
Форматирование, бенчмарки и задачи итераций с 16 по 18 приняты. Но есть стопперы, как минимум два:
1. Неверно реализовано удаление.
2. Бага при работе с БД в области проверки ошибок.

Еще в коде присутствует откровенно лишний слой логики (но это не стоппер).
Все в комментариях к коду.

2024-06-27 21:45 UTC, avhitrov commented on internal/usecase/dbstorage.go
> +	}
Данный блок должен находиться в коде ниже цикла `for rows.Next()`.

При переборе строк rows.Next() возвращает bool, в котором false который может быть результатом как нормального достижения конца списка, так и возникшей ошибки. Поэтому после цикла необходимо проверить, не по ошибке ли мы вывалились, и вернуть эту ошибку.

2024-06-27 21:45 UTC, avhitrov commented on internal/usecase/usecase.go
Поскольку все функции данного слоя представляют собой прокси в репозиторий - слой не нужен.

2024-06-28 10:37 UTC, nextlag commented on internal/controllers/delete.go
> +	err = c.uc.DoDel(r.Context(), uuid, URLs)
У меня логика конкурентности находится в dbstorage функция: updateStatusDel(), я передаю через канал туда все все алиасы, которые необходимо удалить и дальше асинхронно меняю их статусы. Но я добавил в хендлер дополнительно паттерн fanIn, хотя мне кажется - это уже оверхед

2024-06-28 10:38 UTC, nextlag commented on internal/usecase/usecase.go
здесь я просто хотел на практике поиграться с чистой архитектурой.

2024-06-28 10:39 UTC, nextlag commented on internal/usecase/dbstorage.go
> +	}
Поправил

2024-07-03 22:24 UTC, avhitrov commented on internal/controllers/delete.go
> +	err = c.uc.DoDel(r.Context(), uuid, URLs)
Самое главное в задании - асинхронность удаления относительно работы http-хендлера. В первую очередь это означает, что хендлер должен завершаться, не дожидаясь окончания собственно процедуры удаления. Схема Fan-in в этом случае реализуется почти автоматически, так как множество одновременных обращений на удаление создадут несколько горутин (по количеству запросов), которые, даже если просто дернуть функцию удаления, уже сработают по вышеуказанной схеме. Просто точкой сборки в этом случае будет драйвер БД.

Что следует из задания:
1. Процедуру удаления необходимо отвязать от процесса обсчета хендлера. То есть запускать ее необходимо в горутине и не ожидать никакого возврата никаких ошибок или прочих результатов работы со стораджем,
2. В процедуру удаления нельзя пробрасывать контекст от запроса, так как он протухает сразу, как только завершается работа http-хендлера и досрочно прервет обращение к БД.
3. Само удаление в той же БД можно делать в один запрос, используя оператор IN или функцию ANY($2).

2024-07-03 22:24 UTC, avhitrov commented on internal/usecase/dbstorage.go
> +	}
Принято

2024-07-03 22:24 UTC, avhitrov commented on internal/usecase/usecase.go
Принято. Почему-то не могу зарезолвить комментарии.

2024-07-03 22:25 UTC, avhitrov requested changes
Все-таки удаление необходимо сделать асинхронным относительно http-хендлера. Подробности - в комментарии к коду.

2024-07-07 23:00 UTC, avhitrov approved these changes
Все ок.

2024-07-23 14:22 UTC, merged